services:
  web1:
    build: ./web1
    ports:
      - "8081:80"
      - "10051:10050"
    networks:
      app_net:
        ipv4_address: 172.16.0.13

  web2:
    build: ./web2
    ports:
      - "8082:80"
      - "10052:10050"
    networks:
      app_net:
        ipv4_address: 172.16.0.14

  lvs1:
    build: ./lvs1
    container_name: lvs1
    network_mode: "host" # 使用主机网络模式
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules:ro
      - /proc:/proc:rw
    depends_on:
      - web1
      - web2

  lvs2:
    build: ./lvs2
    container_name: lvs2
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules:ro
      - /proc:/proc:rw
    depends_on:
      - web1
      - web2

  keepalived1:
    build: ./keepalived1
    container_name: keepalived1
    network_mode: "host" # web VIP需要host网络
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    depends_on:
      - mysql1
      - lvs1

  keepalived2:
    build: ./keepalived2
    container_name: keepalived2
    network_mode: "host" # web VIP需要host网络
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    depends_on:
      - mysql2
      - lvs2

  mysql1:
    image: mysql:5.7.23
    container_name: mysql1
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./mysql1/my.cnf:/etc/mysql/my.cnf
      - mysql1_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      app_net:
        ipv4_address: 172.16.0.21
    privileged: true

  mysql2:
    image: mysql:5.7.23
    container_name: mysql2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./mysql2/my.cnf:/etc/mysql/my.cnf
      - mysql2_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      app_net:
        ipv4_address: 172.16.0.22
    privileged: true

  dns1:
    build: ./dns1
    container_name: dns1
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
      - "10053:10050"
    networks:
      app_net:
        ipv4_address: 172.16.0.8
    volumes:
      - ./dns1/config:/var/named
    cap_add:
      - NET_ADMIN
    restart: always

  dns2:
    build: ./dns2
    container_name: dns2
    ports:
      - "5354:53/udp"
      - "5354:53/tcp"
      - "10054:10050"
    networks:
      app_net:
        ipv4_address: 172.16.0.9
    volumes:
      - ./dns2/config:/var/named
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - dns1

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-5.0-latest
    environment:
      - DB_SERVER_HOST=mysql1 # 使用主库
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - ZBX_DEBUGLEVEL=3
      - ZBX_STARTPOLLERS=5
      - ZBX_IPMIPOLLERS=0
      - ZBX_STARTPOLLERSUNREACHABLE=1
      - ZBX_STARTTRAPPERS=5
      - ZBX_STARTPINGERS=1
      - ZBX_STARTDISCOVERERS=1
      - ZBX_STARTHTTPPOLLERS=1
    networks:
      app_net:
        ipv4_address: 172.16.0.2 # 固定IP
    depends_on:
      - mysql1
    dns:
      - 114.114.114.114
      - 8.8.8.8
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=mysql1 # 使用主库
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - PHP_TZ=Asia/Shanghai
    ports:
      - "8080:8080"
    networks:
      - app_net
    depends_on:
      - zabbix-server
    restart: always

  nfs-server:
    image: erichough/nfs-server
    privileged: true
    environment:
      - NFS_EXPORT_0=/nfsshare *(rw,no_root_squash,no_subtree_check)
    volumes:
      - ./nfs_data:/nfsshare
    networks:
      app_net:
        ipv4_address: 172.16.0.5

  ntp-server:
    image: cturra/ntp
    container_name: ntp-server
    restart: always
    ports:
      - "123:123/udp"
    environment:
      - NTP_SERVERS=pool.ntp.org
    networks:
      app_net:
        ipv4_address: 172.16.0.6

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16

volumes:
  mysql1_data:
  mysql2_data:
