services:
  web1:
    build: ./web1
    ports:
      - "8081:80"
    networks:
      app_net:
        ipv4_address: 172.16.0.13

  web2:
    build: ./web2
    ports:
      - "8082:80"
    networks:
      app_net:
        ipv4_address: 172.16.0.14

  lvs1:
    build: ./lvs1
    container_name: lvs1
    network_mode: "host" # 使用主机网络模式
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules:ro
      - /proc:/proc:rw
    depends_on:
      - web1
      - web2

  lvs2:
    build: ./lvs2
    container_name: lvs2
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules:ro
      - /proc:/proc:rw
    depends_on:
      - web1
      - web2

  mysql1:
    build: ./mysql1
    container_name: mysql1
    networks:
      app_net:
        ipv4_address: 172.16.0.21  # 使用固定IP
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql1_data:/var/lib/mysql
      - mysql1_run:/var/run/mysqld
    privileged: true
    restart: always

  mysql2:
    build: ./mysql2
    container_name: mysql2
    networks:
      app_net:
        ipv4_address: 172.16.0.22  # 使用固定IP
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql2_data:/var/lib/mysql
      - mysql2_run:/var/run/mysqld
    privileged: true
    restart: always

  keepalived1:
    build: ./keepalived1
    container_name: keepalived1
    network_mode: "host"  
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - mysql1
      - lvs1

  keepalived2:
    build: ./keepalived2
    container_name: keepalived2
    network_mode: "host"
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - mysql2
      - lvs2

volumes:
  mysql1_data:
  mysql2_data:
  mysql1_run:
  mysql2_run:

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
