services:
  web1:
    build: ./web1
    ports:
      - "8081:80"
    networks:
      app_net:
        ipv4_address: 192.168.100.112

  web2:
    build: ./web2
    ports:
      - "8082:80"
    networks:
      app_net:
        ipv4_address: 192.168.100.113

  lvs:
    build: ./lvs
    container_name: lvs-director
    network_mode: "host"  # 使用主机网络模式
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules:ro
      - /proc:/proc:rw
    depends_on:
      - web1
      - web2

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24